export const STATES = Object.freeze({
  ANDHRA_PRADESH: 'ANDHRA_PRADESH',
  ARUNACHAL_PRADESH: 'ARUNACHAL_PRADESH',
  ASSAM: 'ASSAM',
  BIHAR: 'BIHAR',
  CHHATTISGARH: 'CHHATTISGARH',
  GOA: 'GOA',
  GUJARAT: 'GUJARAT',
  HARYANA: 'HARYANA',
  HIMACHAL_PRADESH: 'HIMACHAL_PRADESH',
  JHARKHAND: 'JHARKHAND',
  KARNATAKA: 'KARNATAKA',
  KERALA: 'KERALA',
  MADHYA_PRADESH: 'MADHYA_PRADESH',
  MAHARASHTRA: 'MAHARASHTRA',
  MANIPUR: 'MANIPUR',
  MEGHALAYA: 'MEGHALAYA',
  MIZORAM: 'MIZORAM',
  NAGALAND: 'NAGALAND',
  ODISHA: 'ODISHA',
  PUNJAB: 'PUNJAB',
  RAJASTHAN: 'RAJASTHAN',
  SIKKIM: 'SIKKIM',
  TAMIL_NADU: 'TAMIL_NADU',
  TELANGANA: 'TELANGANA',
  TRIPURA: 'TRIPURA',
  UTTAR_PRADESH: 'UTTAR_PRADESH',
  UTTARAKHAND: 'UTTARAKHAND',
  WEST_BENGAL: 'WEST_BENGAL',

  // Union Territories
  ANDAMAN_AND_NICOBAR_ISLANDS: 'ANDAMAN_AND_NICOBAR_ISLANDS',
  CHANDIGARH: 'CHANDIGARH',
  DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU: 'DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU',
  DELHI: 'DELHI',
  JAMMU_AND_KASHMIR: 'JAMMU_AND_KASHMIR',
  LADAKH: 'LADAKH',
  LAKSHADWEEP: 'LAKSHADWEEP',
  PUDUCHERRY: 'PUDUCHERRY',
});

export type StateKey = keyof typeof STATES;

export const STATE_OPTIONS: { label: string; value: StateKey }[] = Object.keys(STATES).map(
  (key) => ({
    label: key
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (c) => c.toUpperCase())
      .replace(/\bAnd\b/g, 'and'),
    value: key as StateKey,
  })
);
